site_name: Biosigmat
site_description: A MATLAB library for biomedical signal processing (ECG, PPG, respiration) by BSICoS.
repo_url: https://github.com/BSICoS/biosigmat
repo_name: biosigmat

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - minify:
      minify_html: true
  - redirects

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Getting started:
    - Installation: installation.md
  - API:
    - Overview: api/index.md
    - ECG:
      - Overview: api/ecg/index.md
      - Baseline removal: api/ecg/baselineremove.md
      - QRS detection (Pan–Tompkins): api/ecg/pantompkins.md
      - Slope/Range: api/ecg/sloperange.md
    - PPG:
      - Overview: api/ppg/index.md
      - Pulse detection: api/ppg/pulsedetection.md
      - Pulse delineation: api/ppg/pulsedelineation.md
    - HRV:
      - Overview: api/hrv/index.md
      - Time-domain metrics: api/hrv/tdmetrics.md
    - Tools:
      - Overview: api/tools/index.md
      - findsequences: api/tools/findsequences.md
      - interpgap: api/tools/interpgap.md
      - ispeaky: api/tools/ispeaky.md
      - lpdfilter: api/tools/lpdfilter.md
      - medfiltThreshold: api/tools/medfiltThreshold.md
      - nanfilter: api/tools/nanfilter.md
      - nanfiltfilt: api/tools/nanfiltfilt.md
      - nanpwelch: api/tools/nanpwelch.md
      - peakedness: api/tools/peakedness.md
      - slicesignal: api/tools/slicesignal.md
      - slider: api/tools/slider.md
      - snaptopeak: api/tools/snaptopeak.md
      - trimnans: api/tools/trimnans.md
  - Examples:
    - Overview: api/examples/index.md
    - ECG:
      - Baseline remove: api/examples/baselineremoveExample.md
      - Pan–Tompkins: api/examples/pantompkinsExample.md
      - Slope/Range: api/examples/sloperangeExample.md
    - HRV:
      - tdmetrics: api/examples/tdmetricsExample.md
    - PPG:
      - Pulse detection: api/examples/pulsedetectionExample.md
      - Pulse delineation: api/examples/pulsedelineationExample.md
    - Workflows:
      - Cycle averaging: api/examples/pcaverageWorkflow.md
      - Time–frequency maps: api/examples/tfmapWorkflow.md
  - Contribute:
    - Contribution guide: CONTRIBUTING.md
    - Code style: code-style-guide.md
    - License: LICENSE.md
  - Changelog: changelog.md
