classdef verifyBiosiglibExpectedWarningsTest < matlab.unittest.TestCase
    methods (Test)
        function testExpectedWarningAndAffectedIds(tc)
            caseDefinition = struct( ...
                'id', 'tools.example.expected_warning', ...
                'expected_warnings', struct( ...
                    'id', 'example_warning', ...
                    'affected_ids', {{'first', 'second'}}));
            warningIdMap = containers.Map( ...
                {'example_warning'}, ...
                {'biosigmat:test:example_warning'});

            verifyBiosiglibExpectedWarnings( ...
                tc, @emitExampleWarning, caseDefinition, warningIdMap);
        end

        function testNoExpectedOrActualWarnings(tc)
            caseDefinition = struct('id', 'tools.example.no_warning');
            warningIdMap = containers.Map( ...
                {'example_warning'}, ...
                {'biosigmat:test:example_warning'});

            verifyBiosiglibExpectedWarnings( ...
                tc, @() 1, caseDefinition, warningIdMap);
        end

        function testUnmappedUnexpectedWarningFails(tc)
            caseDefinition = struct('id', 'tools.example.unmapped_warning');
            warningIdMap = containers.Map( ...
                {'example_warning'}, ...
                {'biosigmat:test:example_warning'});

            tc.verifyError(@() verifyBiosiglibExpectedWarnings( ...
                tc, @emitUnmappedWarning, caseDefinition, warningIdMap), ...
                'biosigmat:UnexpectedWarning');
        end
    end
end

function emitExampleWarning()
warning('biosigmat:test:example_warning', ...
    'example_warning affected_ids: second, first');
end

function emitUnmappedWarning()
warning('biosigmat:test:unmapped_warning', ...
    'This warning is intentionally absent from the canonical map.');
end
