name: Check MATLAB Examples

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  check-matlab-examples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for corresponding example files
        run: |
          echo "Searching for MATLAB function files and corresponding examples..."

          # Find all .m files in src/** (excluding hidden dirs, private folders, and tools folder)
          find src -type f -name '*.m' | grep -v '/private/' | grep -v '/tools/' | while read -r srcfile; do
            # Get the function name without extension
            funcname=$(basename "$srcfile" .m)
            
            # Expected corresponding example file
            expected_examplefile="examples/${srcfile#src/}"
            expected_examplefile="${expected_examplefile%.*}Example.m"

            # Check if the example file exists
            if [ ! -f "$expected_examplefile" ]; then
              echo "::error file=$srcfile::Missing corresponding example file: $expected_examplefile"
              exit 1
            fi
          done

          echo "All MATLAB functions (except tools) have corresponding example files!"
