name: MATLAB Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2024b
        cache: true
    
    - name: Run tests
      uses: matlab-actions/run-command@v2
      with:
        command: |
          try
            runTestsCI;
            fprintf('All tests passed successfully!\n');
          catch ME
            fprintf('Test execution failed: %s\n', ME.message);
            exit(1);
          end
    
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: MATLAB Test Results
        path: test-results.xml
        reporter: java-junit
        fail-on-error: true
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          test-results.xml
          coverage.xml
        retention-days: 30
