name: MATLAB Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2024b
        cache: true
    
    - name: Verify MATLAB installation
      uses: matlab-actions/run-command@v2
      with:
        command: |
          fprintf('=== MATLAB Online Diagnostic ===\n');
          fprintf('MATLAB Version: %s\n', version);
          fprintf('License: %s\n', license);
          fprintf('Platform: %s\n', computer);
          fprintf('Available toolboxes:\n');
          installedToolboxes = ver;
          for i = 1:length(installedToolboxes)
              fprintf('  - %s %s\n', installedToolboxes(i).Name, installedToolboxes(i).Version);
          end
          fprintf('=== End Diagnostic ===\n');
    
    - name: Run tests
      uses: matlab-actions/run-command@v2
      with:
        command: |
          try
            runTestsCI;
            fprintf('All tests passed successfully!\n');
          catch ME
            fprintf('Test execution failed: %s\n', ME.message);
            exit(1);
          end
    
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: MATLAB Test Results
        path: test-results.xml
        reporter: java-junit
        fail-on-error: true
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          test-results.xml
          coverage.xml
        retention-days: 30
